baseURL = 'https://cyberbezpeka.net/'
languageCode = 'uk-ua'
title = 'Кібербезпека UA'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = 'auto' # Тема підлаштовуватиметься під систему користувача (світла/темна)
  ShowPostNavLinks = true

  [params.analytics.google]
    id = "G-W2ME3VSWFQ"

  [params.search]
    enable = true
    placeholder = "Пошук..."
    mode = "full"
    fuseOpts = { threshold = 0.4, distance = 100, ignoreLocation = true }
  
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "search"
    name = "🔍 Пошук"
    url = "/search/"
    weight = 5
    
[[menu.main]]
    identifier = "tags"
    name = "Фільтри (Теги)"
    url = "/tags/"
    weight = 10
	
[params.cover]
hiddenInList = false
hiddenInSingle = false
